name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
     - 'v*'
    branches:
      - main
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  PYEDB_USE_LEGACY: '1'
  PYEDB_CI_NO_DISPLAY: '1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  legacy-test:
    name: "Check legacy tests"
    runs-on: [ windows, pyedb, self-hosted ]
    steps:
      - name: "Install Git and clone project"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: ansys/actions/_setup-python@main
        with:
          python-version: '3.10'
          use-cache: false

      - name: Create Python venv
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1

      - name: "Update pip"
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install -U pip

      - name: "Install Python library"
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install .

      - name: "Install test requirements"
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install .[tests]

      - name: "Executing legacy unit tests"
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -m "legacy and unit" -n auto --dist loadfile -v

      - name: "Executing legacy system tests (distributing on multiple CPUs)"
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -m "legacy and system and not no_xdist" -n auto --dist loadfile -v
